apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argo-cd
spec:
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 0-argocd-apps
    repoURL: https://github.com/hazim1093/backstage-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
