apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appOfApps
  namespace: argo-cd
spec:
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  project: argocd-apps
  source:
    path: 0-argocd-apps
    repoUrl: https://github.com/hazim1093/backstage-demo
