apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: components
  source:
    path: components/ingress-nginx
    repoUrl: https://github.com/hazim1093/backstage-demo
