renovate:
  cronjob:
    schedule: "0 * * * *" # Every hour at minute 0
    failedJobsHistoryLimit: 3
    successfulJobsHistoryLimit: 3
    jobBackoffLimit: 5
    parallelism: 0

  envFrom:
  - secretRef:
      name: renovate-secrets

  renovate:
    config: |
      {
        "extends": [
          "config:base"
        ],
        "platform": "github",
        "autodiscover": "false",
        "printConfig": true,
        "repositories": ["hazim1093/backstage-demo"]
      }
